version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: mediago
    depends_on:
      - mysql

  mysql:
    image: m.daocloud.io/docker.io/library/mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mediago
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
