name: Deploy MediaGo Docs

on:
  push:
    paths:
      - "docs/**"
      - ".github/actions/setup-ossutil/**"
      - ".github/workflows/build-docs.yml"
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  OSS_BUCKET: downloader-docs
  OSS_ENDPOINT: oss-cn-beijing.aliyuncs.com
  OSS_REGION: cn-beijing

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: go-task/setup-task@v1
        with:
          version: "3.51.1"

      - uses: pnpm/action-setup@v5
        with:
          run_install: false
          standalone: true

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.14.0"
          cache: "pnpm"

      - name: Build with Vitepress
        run: task ci:docs:build

      - name: Setup Alibaba Cloud ossutil
        uses: ./.github/actions/setup-ossutil
        with:
          version: "2.3.0"

      - name: Upload documentation to Alibaba Cloud OSS
        env:
          OSS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
        run: ossutil cp docs/.vitepress/dist "oss://${OSS_BUCKET}" -r -f
